### ISSUE TITLE
[명품자바프로그래밍 복습2 할일 및 일정 관리]

### ISSUE THREAD

**Issue by bisoya** [jectgenius/luxury_java_programming_review1#1]
# 🌈 Success criteria
1. 

# 👷To-do
- [ ] 깃허브 프로젝트 생성
- [ ] 깃허브 마일스톤 생성
- [ ] 깃허브 이슈 작성 및 담당자 할당
- [ ] 깃허브 이슈들을 마일스톤 단위로 묶기

# 👓 Review
1.
