### ISSUE TITLE
[이론] 8장 입출력 스트림과 파일 입출력

### ISSUE THREAD

**Issue by bisoya** [jectgenius/luxury_java_programming_review1#10]
# 🌈 Success criteria
1. 강의
2. 필기
3. 문제 (checktime, 이론문제)

# 👷To-do
- [ ] 강의 듣기 // 졸지 않기 위해서 일어서거나 노트에 적으면서 듣기
- [ ] 강의 들으면서 캡쳐
- [ ] 강의 들으면서 필기 
- [ ] 캡쳐본 정리 // 누락, 순서, 캡쳐도구
- [ ] 필기 정리 // 블로그 포스팅
- [ ] 필기 읽기 // 고쳐야할 곳이 있는지 검토
- [ ] 필기 암기 // 눈으로 암기
- [ ] 필기 백지복습 // 체크용
- [ ] 문제 풀기 (checktime, 이론문제) // 답+이유, 블로그 포스팅(정답 공유 포스팅)용
- [ ] 문제 채점 // 빨간색으로 표시(교재에)
- [ ] 문제 다시 볼 문제 정리 // 블로그 포스팅(개인 복습 위한 다시 볼 문제 정리 포스팅)용

# 👓 Review
1.
