### ISSUE TITLE
[실습] 1장 자바 시작

### ISSUE THREAD

**Issue by bisoya** [jectgenius/luxury_java_programming_review1#13]
# 🌈 Success criteria
1. 예제
2. 실습문제
3. OpenChallenge

# 👷To-do
- [x] 예제 코딩
- [x] 예제 실행
- [x] 예제 주석 // 1. 문법
- [x] 예제 주석 // 2. 큰 흐름
- [x] 실습문제 주석 // 1. 계획
- [x] 실습문제 코딩
- [x] 실습문제 실행
- [x] 실습문제 주석 // 2. 문법
- [x] 실습문제 커밋
- [x] OpenChallenge 주석 // 1. 계획
- [x] OpenChallenge 코딩
- [x] OpenChallenge 실행
- [x] OpenChallenge 주석 // 2. 문법
- [x] OpenChallenge 커밋

# 👓 Review
1.
