### ISSUE TITLE
[실습] 2장 자바 기본 프로그래밍

### ISSUE THREAD

**Issue by bisoya** [jectgenius/luxury_java_programming_review1#14]
# 🌈 Success criteria
1. 예제
2. 실습문제
3. OpenChallenge

# 👷To-do
- [x] 예제 코딩
- [x] 예제 실행
- [x] 예제 주석 // 1. 문법
- [x] 예제 주석 // 2. 큰 흐름
- [ ] 실습문제 주석 // 1. 계획
- [ ] 실습문제 코딩
- [ ] 실습문제 실행
- [ ] 실습문제 주석 // 2. 문법
- [ ] 실습문제 커밋
- [ ] OpenChallenge 주석 // 1. 계획
- [ ] OpenChallenge 코딩
- [ ] OpenChallenge 실행
- [ ] OpenChallenge 주석 // 2. 문법
- [ ] OpenChallenge 커밋

# 👓 Review
1.
