### ISSUE TITLE
[실습] 3장 반복문과 배열 그리고 예외 처리

### ISSUE THREAD

**Issue by bisoya** [jectgenius/luxury_java_programming_review1#15]
# 🌈 Success criteria
1. 예제
2. 실습문제
3. OpenChallenge

# 👷To-do
- [ ] 예제 코딩
- [ ] 예제 실행
- [ ] 예제 주석 // 1. 문법
- [ ] 예제 주석 // 2. 큰 흐름
- [ ] 실습문제 주석 // 1. 계획
- [ ] 실습문제 코딩
- [ ] 실습문제 실행
- [ ] 실습문제 주석 // 2. 문법
- [ ] 실습문제 커밋
- [ ] OpenChallenge 주석 // 1. 계획
- [ ] OpenChallenge 코딩
- [ ] OpenChallenge 실행
- [ ] OpenChallenge 주석 // 2. 문법
- [ ] OpenChallenge 커밋

# 👓 Review
1.
